require("plugins.packer")
require("plugins.telescope")
require("plugins.colour")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.harpoon")
require("plugins.fugative")
require("plugins.neotree")
require("plugins.barbar")
require("plugins.toggleterm")
require("plugins.lualine")
require("plugins.noice")
require("plugins.blankline")
require("plugins.mini")


